// Trains the trail-report filter on tools/classifier/seed.tsv, reports 5-fold cross-validated
// accuracy, precision and recall, then writes the weights to app/src/main/assets/web/js/reportfilter-model.js.
// Usage: node tools/classifier/train.js
const fs = require('fs'), path = require('path');
const F = require('../../app/src/main/assets/web/js/reportfilter.js');

const rows = fs.readFileSync(path.join(__dirname, 'seed.tsv'), 'utf8').trim().split('\n').map(l => { const [y, ...t] = l.split('\t'); return { y: +y, text: t.join('\t') }; });
let seed = 42;
const rand = () => { seed = (seed * 1103515245 + 12345) & 0x7fffffff; return seed / 0x7fffffff; };
const shuffle = (a) => { for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(rand() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; } return a; };

const EPOCHS = 80, LR = 0.2, L2 = 1e-4;
function train(data) {
  const m = new F.Model();
  for (let e = 0; e < EPOCHS; e++) shuffle(data.slice()).forEach(r => m.step(r.text, r.y, LR * (1 - e / EPOCHS * 0.7), L2));
  return m;
}

// 5-fold cross validation
const data = shuffle(rows.slice());
const K = 5, TH = 0.6;
let tp = 0, fp = 0, tn = 0, fn = 0;
for (let k = 0; k < K; k++) {
  const test = data.filter((_, i) => i % K === k), tr = data.filter((_, i) => i % K !== k);
  const m = train(tr);
  test.forEach(r => { const p = m.score(r.text) >= TH; if (p && r.y) tp++; else if (p) fp++; else if (r.y) fn++; else tn++; });
}
const acc = (tp + tn) / data.length, prec = tp / Math.max(1, tp + fp), rec = tp / Math.max(1, tp + fn);
console.log(`examples ${data.length} (reports ${rows.filter(r => r.y).length}, noise ${rows.filter(r => !r.y).length})`);
console.log(`5-fold cross-validation at threshold ${TH}: accuracy ${(acc * 100).toFixed(1)}%, precision ${(prec * 100).toFixed(1)}%, recall ${(rec * 100).toFixed(1)}%`);

const m = train(data);
const w = Array.from(m.w).map(x => Math.round(x * 1e4) / 1e4);
const out = '/* Generated by tools/classifier/train.js from tools/classifier/seed.tsv. Do not edit by hand. */\n' +
  `window.BcReportModel = { trained: '${new Date().toISOString().slice(0, 10)}', examples: ${data.length}, cv: { accuracy: ${acc.toFixed(3)}, precision: ${prec.toFixed(3)}, recall: ${rec.toFixed(3)} }, b: ${m.b.toFixed(4)}, w: [${w.join(',')}] };\n`;
fs.writeFileSync(path.join(__dirname, '../../app/src/main/assets/web/js/reportfilter-model.js'), out);
console.log('wrote reportfilter-model.js', (out.length / 1024).toFixed(1), 'KB');

// A few unseen sanity checks
const probes = [
  ['Trail to Blue Lake is covered in ice past the bridge this morning, spikes needed.', 1],
  ['Big sale on hiking socks this week only, 25% off!', 0],
  ['Who is running for governor this year?', 0],
  ['Mud and blowdowns on the lower section today, upper trail dry.', 1],
  ['Such a pretty day for a walk.', 0],
  ['Sentier glacé ce matin au sommet, crampons nécessaires.', 1],
  ['El sendero está cerrado hoy por nieve en el paso.', 1]
];
probes.forEach(([t, y]) => console.log((Math.round(m.score(t) * 100) + '%').padStart(5), y ? 'report' : 'noise ', t));
